image: python:3.10

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install wheel
  - pip install --requirement requirements.txt

stages:
  - exec-solution

exec-solution:
  stage: exec-solution
  script:
    - python solution.py
  tags:
    - shared-fi
